### ISSUE TITLE
The ProteinRoBERTa model

### ISSUE THREAD

**Issue by toooooodo** [boun-tabi/biochemical-lms-for-drug-design#2]
Hi, thank you very much for sharing this great work.

However, I have encountered an issue. The source code relies on the pretrained ProteinRoBERTa model, but it appears that the ProteinRoBERTa model is not available in HuggingFace's official model repository. I would like to know if there is an alternative source or repository from which the model can be obtained. 

Once again, I want to express my admiration for the authors' work and thank you in advance for any assistance provided in addressing this issue.

**Comment by gokceuludogan** [comment]
Hi,

Thank you for your kind words and your interest in our work.

You may access the model weights through [this link](https://ibm.ent.box.com/v/paccmann-proteomics-data/folder/125694001198).

If you have any further questions or need assistance, please let us know.

Best regards,
Gökçe

**Comment by toooooodo** [comment]
Thank you for your timely reply. It solves the issue! :)
