### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by toooooodo** [boun-tabi/biochemical-lms-for-drug-design#3]
I apologize for bothering you again. 

I am feeling a bit puzzled regarding the dataset. I have noticed that there are two versions available for the validation and test dataset: one with "uniq" and one without.  I am uncertain about the reason behind having two versions of the dataset and their respective purposes.  I would greatly appreciate it if you could kindly provide some clarification on this matter. Thank you for your patience and assistance.

**Comment by gokceuludogan** [comment]
No problem at all. I'm happy to help you. The "uniq" versions of the dataset contain only one record per protein rather than all interactions. They are primarily designed for convenience during generation, as they only require protein information. They don't serve any other specific purpose.

**Comment by toooooodo** [comment]
Thank you for your kindly response and for resolving the issue!
